version: "3.9"

services:
  wallet-service:
    build: .
    container_name: wallet-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - MONGODB_URI=${MONGODB_URI:-mongodb://localhost:27017/Wallet-db}
      - MONGODB_DATABASE=Wallet-db
    networks:
      - eciexpress-network

networks:
  eciexpress-network:
    driver: bridge
